// Package jobScheduler Code generated by swaggo/swag. DO NOT EDIT
package jobScheduler

import "github.com/swaggo/swag"

const docTemplatejobScheduler = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/messenger/is-working": {
            "get": {
                "description": "Checks whether the Messenger Job is currently running.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MessengerJob"
                ],
                "summary": "Check Messenger Job Status",
                "responses": {
                    "200": {
                        "description": "Current job status",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponse"
                        }
                    },
                    "500": {
                        "description": "Internal server error",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponse"
                        }
                    }
                }
            }
        },
        "/messenger/start": {
            "get": {
                "description": "Initiates the Messenger Job and returns the operation status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MessengerJob"
                ],
                "summary": "Start Messenger Job",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "bad request",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponse"
                        }
                    }
                }
            }
        },
        "/messenger/stop": {
            "get": {
                "description": "Terminates the Messenger Job and returns the operation status.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "MessengerJob"
                ],
                "summary": "Stop Messenger Job",
                "responses": {
                    "200": {
                        "description": "success",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid request",
                        "schema": {
                            "$ref": "#/definitions/pkg.BaseResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "pkg.BaseResponse": {
            "type": "object",
            "properties": {
                "data": {},
                "internalCode": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                },
                "status": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfojobScheduler holds exported Swagger Info so clients can modify it
var SwaggerInfojobScheduler = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:3001",
	BasePath:         "/job-scheduler",
	Schemes:          []string{},
	Title:            "Job Scheduler",
	Description:      "This is the API documentation for the Job Scheduler service.",
	InfoInstanceName: "jobScheduler",
	SwaggerTemplate:  docTemplatejobScheduler,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfojobScheduler.InstanceName(), SwaggerInfojobScheduler)
}
